### ISSUE TITLE
Support for ACF 5

### ISSUE THREAD

**Issue by lewebsimple** [hcmedia/acf-field-phonenumber#2]
I'm trying to use this plugin with ACF Pro 5 and can't seem to get it working.

I changed the comments so the plugin loads `acf-phonenumber-v5.php` and adjusted the code there so it wouldn't throw an error (acf_field_randomstring was used instead of acf_field_phonenumber), but it seems the work isn't done.

Am I missing anything?

We really need this so I'll probably fork this repository in the near future and submit a pull request once I get it working.

**Comment by jackfearing** [comment]
+1

**Comment by lewebsimple** [comment]
@jackfearing check this out, I've created a new phone field plugin for ACF 5 with dynamic input validation, optional extension support and National / E.164 / Click to Call / Array formatting options.
https://github.com/lewebsimple/acf-phone

**Comment by jackfearing** [comment]
Thanks Lewebsimple, I just installed the plugin from the link above and it's works perfectly. Really saved the day --- thanks!

**Comment by jackfearing** [comment]
Thanks Lewebsimple, Have you already updated your repo with the new updates from the link above?
